version: '3.1'
volumes:
  db-mongo:
  db-redis:
services:
  mongo:
    image: mongo:5.0.5
    restart: unless-stopped 
    volumes:
      - db-mongo:/data/db
  redis:
    image: redis:6.2.6
    restart: unless-stopped 
    ports:
      - "26379:6379"
    volumes:
      - db-redis:/data
  nats:
    image: nats
    restart: unless-stopped 
    ports:
      - 4222:4222 
      - 6222:6222 
      - 8222:8222 
  broker_grpc:
    image: docker.clhero.fun/hero/micro_broker_grpc:master
    build: 
      context: ../broker/connect/grpc
      dockerfile: ../../../upmicro/Dockerfile
    environment:
      - SERVE_NAME=broker
      - NATS_URL=nats:4222
      - JWT_TOKEN_KEY=lkk123
      - DEBUG_LOG=true
    ports:
      - 9090:9090 #grpc
  broker_http:
    image: docker.clhero.fun/hero/micro_broker_http:master
    build: 
      context: ../broker/connect/http
      dockerfile: ../../../upmicro/Dockerfile
    environment:
      - SERVE_NAME=broker
      - NATS_URL=nats:4222
      - JWT_TOKEN_KEY=lkk123
      - DEBUG_LOG=true
    ports:
      - 8080:8080 #http
  broker_tcp:
    image: docker.clhero.fun/hero/micro_broker_tcp:master
    build: 
      context: ../broker/connect/tcp
      dockerfile: ../../../upmicro/Dockerfile
    environment:
      - SERVE_NAME=broker
      - NATS_URL=nats:4222
      - JWT_TOKEN_KEY=lkk123
      - DEBUG_LOG=true
    ports:
      - 7070:7070 #http

  broker_web:
    image: docker.clhero.fun/hero/micro_broker_web:master
    build: 
      context: ../broker/connect/web
      dockerfile: ../../../upmicro/Dockerfile
    environment:
      - SERVE_NAME=broker
      - NATS_URL=nats:4222
      - JWT_TOKEN_KEY=lkk123
      - DEBUG_LOG=true
    ports:
      - 8888:8080 #http
  